# Generated by Django 3.2.16 on 2022-11-27 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.CharField(max_length=8, verbose_name='Temperatura')),
                ('pressao', models.CharField(max_length=11, verbose_name='Pressão')),
                ('altitude', models.CharField(max_length=11, verbose_name='Altitude')),
                ('pressa_nivel_mar', models.CharField(max_length=11, verbose_name='Pressão a nível do mar')),
                ('altitude_real', models.CharField(max_length=11, verbose_name='Altitude real')),
                ('data_registro', models.DateTimeField(auto_now=True, verbose_name='Data do registro')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Device.sensor', verbose_name='Identificação do Sensor')),
            ],
        ),
    ]
