# Generated by Django 3.2.16 on 2022-11-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataLogSensor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='precipitacao',
            field=models.CharField(max_length=11, null=True, verbose_name='Precipitação'),
        ),
    ]
