# Generated by Django 4.0.5 on 2022-12-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataLogSensor', '0002_registro_precipitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='altitude',
            field=models.CharField(blank=True, max_length=11, verbose_name='Altitude'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='altitude_real',
            field=models.CharField(blank=True, max_length=11, verbose_name='Altitude real'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='precipitacao',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Precipitação'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='pressa_nivel_mar',
            field=models.CharField(blank=True, max_length=11, verbose_name='Pressão a nível do mar'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='pressao',
            field=models.CharField(blank=True, max_length=11, verbose_name='Pressão'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='temperatura',
            field=models.CharField(blank=True, max_length=8, verbose_name='Temperatura'),
        ),
    ]
