# Generated by Django 3.2.16 on 2023-04-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataLogSensor', '0003_alter_registro_altitude_alter_registro_altitude_real_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='altitude',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='altitude_real',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='precipitacao',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='pressa_nivel_mar',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='temperatura',
        ),
        migrations.AddField(
            model_name='registro',
            name='date',
            field=models.CharField(blank=True, max_length=8, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='registro',
            name='direcao',
            field=models.CharField(blank=True, max_length=8, verbose_name='dir'),
        ),
        migrations.AddField(
            model_name='registro',
            name='mm_dia',
            field=models.CharField(blank=True, max_length=8, verbose_name='mm_dia'),
        ),
        migrations.AddField(
            model_name='registro',
            name='mm_h',
            field=models.CharField(blank=True, max_length=8, verbose_name='mm_h'),
        ),
        migrations.AddField(
            model_name='registro',
            name='temp',
            field=models.CharField(blank=True, max_length=8, verbose_name='temp'),
        ),
        migrations.AddField(
            model_name='registro',
            name='time',
            field=models.CharField(blank=True, max_length=8, verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='registro',
            name='umidade',
            field=models.CharField(blank=True, max_length=8, verbose_name='umidade'),
        ),
        migrations.AddField(
            model_name='registro',
            name='uv',
            field=models.CharField(blank=True, max_length=8, verbose_name='uv'),
        ),
        migrations.AddField(
            model_name='registro',
            name='vmax',
            field=models.CharField(blank=True, max_length=8, verbose_name='vmax'),
        ),
        migrations.AddField(
            model_name='registro',
            name='vmed',
            field=models.CharField(blank=True, max_length=8, verbose_name='vmed'),
        ),
        migrations.AddField(
            model_name='registro',
            name='w_m2',
            field=models.CharField(blank=True, max_length=8, verbose_name='w_m2'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='pressao',
            field=models.CharField(blank=True, max_length=8, verbose_name='pressao'),
        ),
    ]
