# Generated by Django 3.2.16 on 2023-06-10 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0003_alter_sensor_local'),
        ('DataLogSensor', '0005_auto_20230429_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='date',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='mm_dia',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='mm_h',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='pressao',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='temp',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='time',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='umidade',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='vmax',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='vmed',
        ),
        migrations.AddField(
            model_name='registro',
            name='data',
            field=models.CharField(blank=True, max_length=10, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='registro',
            name='estacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Device.sensor', verbose_name='Identificação da Estação'),
        ),
        migrations.AddField(
            model_name='registro',
            name='hora',
            field=models.CharField(blank=True, max_length=8, verbose_name='Hora'),
        ),
        migrations.AddField(
            model_name='registro',
            name='mm_ciclo',
            field=models.CharField(blank=True, max_length=8, verbose_name='mm/ciclo'),
        ),
        migrations.AddField(
            model_name='registro',
            name='pressao_max',
            field=models.CharField(blank=True, max_length=8, verbose_name='Pressao Máxima'),
        ),
        migrations.AddField(
            model_name='registro',
            name='pressao_media',
            field=models.CharField(blank=True, max_length=8, verbose_name='Pressao Média'),
        ),
        migrations.AddField(
            model_name='registro',
            name='pressao_min',
            field=models.CharField(blank=True, max_length=8, verbose_name='Pressao Mínima'),
        ),
        migrations.AddField(
            model_name='registro',
            name='temp_max',
            field=models.CharField(blank=True, max_length=8, verbose_name='Temperatura Máxima'),
        ),
        migrations.AddField(
            model_name='registro',
            name='temp_media',
            field=models.CharField(blank=True, max_length=8, verbose_name='Temperatura Média'),
        ),
        migrations.AddField(
            model_name='registro',
            name='temp_min',
            field=models.CharField(blank=True, max_length=8, verbose_name='Temperatura Mínima'),
        ),
        migrations.AddField(
            model_name='registro',
            name='umidade_max',
            field=models.CharField(blank=True, max_length=8, verbose_name='Umidade Máxima'),
        ),
        migrations.AddField(
            model_name='registro',
            name='umidade_media',
            field=models.CharField(blank=True, max_length=8, verbose_name='Umidade Média'),
        ),
        migrations.AddField(
            model_name='registro',
            name='umidade_min',
            field=models.CharField(blank=True, max_length=8, verbose_name='Umidade Mínima'),
        ),
        migrations.AddField(
            model_name='registro',
            name='vm_max',
            field=models.CharField(blank=True, max_length=8, verbose_name='Velocidade Máxima'),
        ),
        migrations.AddField(
            model_name='registro',
            name='vm_media',
            field=models.CharField(blank=True, max_length=8, verbose_name='Velocidade Média'),
        ),
        migrations.AddField(
            model_name='registro',
            name='vm_min',
            field=models.CharField(blank=True, max_length=8, verbose_name='Velocidade Mínima'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='direcao',
            field=models.CharField(blank=True, max_length=8, verbose_name='Direção do vento'),
        ),
    ]
