# Generated by Django 3.2.16 on 2023-06-10 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0003_alter_sensor_local'),
        ('DataLogSensor', '0006_auto_20230610_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='estacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Device.sensor', verbose_name='Identificação da Estação'),
        ),
    ]
