# Generated by Django 3.2.16 on 2023-06-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataLogSensor', '0007_alter_registro_estacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='pressao_max',
            field=models.CharField(blank=True, max_length=8, verbose_name='Pressão Máxima'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='pressao_min',
            field=models.CharField(blank=True, max_length=8, verbose_name='Pressão Mínima'),
        ),
    ]
