# Generated by Django 3.2.16 on 2022-11-27 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True, verbose_name='Tipo do sensor')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(max_length=30, verbose_name='Nome do sensor')),
                ('local', models.CharField(max_length=11, verbose_name='Local de Instalação')),
                ('macaddress', models.CharField(max_length=11, unique=True, verbose_name='Endereço MAC')),
                ('data_cadastro', models.DateField()),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Device.tipo')),
            ],
            options={
                'ordering': ['data_cadastro'],
            },
        ),
    ]
