# Generated by Django 3.2.16 on 2023-04-30 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0002_sensor_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='local',
            field=models.CharField(max_length=30, verbose_name='Local de Instalação'),
        ),
    ]
