# Generated by Django 3.2.16 on 2023-09-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0003_alter_sensor_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor',
            field=models.CharField(max_length=30, verbose_name='Nome da Estação'),
        ),
    ]
